[project]
name = "mscthesis"
version = "0.1.0"
description = "Evaluation of climate information integrity in LLMs"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.116.0",
    "datasets>=5.0.0",
    "kagglehub[pandas-datasets]>=1.0.2",
    "matplotlib>=3.11.1",
    "openai>=2.45.0",
    "python-dotenv>=1.2.2",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
